package com.f1soft.campaign.web.constant;

public interface KeyConstant {

    public interface CachedData{
        String HOME_PRODUCT_IMAGE_ALL = "CACHED_DATA_HOME_PRODUCT_IMAGE";
        String FONEPAY_DIRECT_BANK_LIST_ALL = "CACHED_DATA_FONEPAY_DIRECT_BANK_LIST";
        String FONEPAY_HUB_MERCHANT_ALL = "CACHED_DATA_FONEPAY_HUB_MERCHANT";
        String CUSTOMER_ACTIVITY_TYPE_ALL = "CACHED_DATA_CUSTOMER_ACTIVITY_TYPE";
        String CONNECTIPS_CHARGE_LIST_ALL = "CACHED_DATA_CONNECTIPS_CHARGE_LIST";
        String FONEPAY_IBFT_CHARGE_LIST_ALL = "CACHED_DATA_FONEPAY_IBFT_CHARGE_LIST";
        String MAIN_BANNER_ALL = "CACHED_DATA_MAIN_BANNER";
        String CALCULATED_PAYMENT_CHARGE = "CACHED_DATA_CALCULATED_PAYMENT_CHARGE";
        String MOBILE_TOPUP_LIST = "CACHED_DATA_MOBILE_TOPUP_LIST";
    }

    public interface ServiceConfig {
        String ESEWA_CONFIG = "SERVICE_CONFIG_ESEWA";
        String TOPUP_CONFIG = "SERVICE_CONFIG_TOPUP";
        String RECHARGE_CARD_CONFIG = "SERVICE_CONFIG_RECHARGE_CARD";
        String FONEPAY_IBFT_CONFIG = "SERVICE_CONFIG_FONEPAY_IBFT";
        String CONVERGENT_CONFIG = "SERVICE_CONFIG_CONVERGENT";
        String BANCSCONNECT_CONFIG = "SERVICE_CONFIG_BANCSCONNECT";
        String CBS_THREAD_CONFIG = "SERVICE_CONFIG_CBS_THREAD";
        String CAS_CONFIG = "SERVICE_CONFIG_CAS";
        String PASSWORD_CONFIG = "SERVICE_CONFIG_PASSWORD";
        String MPIN_CONFIG = "SERVICE_CONFIG_MPIN";
        String ADMIN_PASSWORD_CONFIG = "SERVICE_CONFIG_ADMIN_PASSWORD";
        String APP_CONFIG = "SERVICE_CONFIG_APP";
        String FONEPAY_HUB_CONFIG = "SERVICE_CONFIG_FONEPAY_HUB";
        String FONEPAY_REWARD_CONFIG = "SERVICE_CONFIG_FONEPAY_REWARD";
        String MINIO_CONFIG = "SERVICE_CONFIG_MINIO";
        String NOTIFICATION_CONFIG = "SERVICE_CONFIG_NOTIFICATION";
        String FONEPAY_DIRECT_CONFIG = "SERVICE_CONFIG_FONEPAY_DIRECT";
        String FORGOT_PASSWORD_CONFIG = "SERVICE_CONFIG_FORGOT_PASSWORD";
        String VERSION_CONFIG = "SERVICE_CONFIG_VERSION";
        String DEFAULT_CONFIG = "SERVICE_CONFIG_DEFAULT";
        String APP_STORE_CONFIG = "SERVICE_CONFIG_APP_STORE";
        String CUSTOMER_CARE_CONFIG = "SERVICE_CONFIG_CUSTOMER_CARE";
        String SOCIAL_NETWORK_CONFIG = "SERVICE_CONFIG_SOCIAL_NETWORK";
        String ADMIN_CONFIG = "SERVICE_CONFIG_ADMIN";
        String RUNNER_CONFIG = "SERVICE_CONFIG_RUNNER";
        String MAINTENANCE_CONFIG = "SERVICE_CONFIG_MAINTENANCE";
        String CONTACT_DETAIL_CONFIG = "SERVICE_CONFIG_CONTACT_DETAIL";
        String SMS_SENDER_CONFIG = "SERVICE_CONFIG_SMS_SENDER";
        String ALERT_SERVER_CONFIG = "SERVICE_CONFIG_ALERT_SERVER";
        String SOCKET_SERVER_CONFIG = "SERVICE_CONFIG_SOCKET_SERVER";

    }

    public interface DataConfig {
        String FEATURE_DATA = "DATA_CONFIG_FEATURE";
        String UTL_DATA = "DATA_CONFIG_UTL";
        String CREDIT_CARD_DATA = "DATA_CONFIG_CREDIT_CARD";
        String CUSTOMER_ACTIVITY_TYPE_DATA = "DATA_CONFIG_CUSTOMER_ACTIVITY_TYPE";
        String MERCHANT_DATA = "DATA_CONFIG_MERCHANT";
        String HMAC_CLIENT_DATA = "DATA_CONFIG_HMAC_CLIENT";
        String APPLICATION_PATTERN_DATA = "DATA_CONFIG_APPLICATION_PATTERN";
        String VENDOR_ENCRYPTION_KEY_DATA = "DATA_CONFIG_VENDOR_ENCRYPTION_KEY";
        String API_SERVER_INFO_DATA = "DATA_CONFIG_API_SERVER_INFO";
        String CBS_QUERY_DATA = "DATA_CONFIG_CBS_QUERY";
        String ACCESSIBLE_CHANNEL_DATA = "DATA_CONFIG_ACCESSIBLE_CHANNEL";
        String CHANNEL_DATA = "DATA_CONFIG_CHANNEL";
    }

    public interface Message {
        String CUSTOMER_MESSAGE = "MESSAGE_CUSTOMER";
        String ADMIN_MESSAGE = "'MESSAGE_ADMIN";
    }
}
