server:
  port: 9090
  servlet:
    context-path: /callgram

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
  jackson:
    default-property-inclusion: NON_NULL

  datasource:
    url: jdbc:mysql://localhost/callgram
    username: root
    password: root
    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
    driver-class-name: com.mysql.cj.jdbc.Driver

#EMAIL PROPERTIES
#EMAIL SCHEDULER RUNS EVERY MINUTE
mail:
  host: smtp.gmail.com
  username: dolletulsi@gmail.com
  password: CatalaN!29
  port: 465
  protocol: smtp
  schedulerTime: 60000
  enabled: N

origin:
  admin: 'http://localhost:4200,http://localhost:4201'
